plugins.treesitter ={
    {
        "nvim-treesitter/nvim-treesitter",
        config ={
            ensure_installed = {
                "bash",
                "c",
                "c_sharp",
                "cmake",
                "devicetree",
                "dockerfile",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "go",
                "graphql",
                "help",
                "html",
                "htmldjango",
                "http",
                "javascript",
                "json",
                "jsonnet",
                "JSON with comments",
                "jq",
                "llvm",
                "lua", 
                "make",
                "markdown",
                "markdown_inline",
                "perl",
                "php",
                "phpdoc",
                "python",
                "racket",
                "ruby",
                "rust",
                "sql",
                "swift",
                "todotxt",
                "toml",
                "typescript",
                "vim", 
                "yaml",
            },
            sync_install = false,
        },
    },
    {
        "nvim-treesitter/nvim-treesitter-context",
        dependencies = "nvim-treesitter/nvim-treesitter",
    },
}
